import type { Metadata } from "next";
import ToasterProvider from "./ToasterProvider";
//import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import { Outfit } from 'next/font/google';



const outfit = Outfit({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'], // Choose what you need
  variable: '--font-outfit',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Liquidity",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${outfit.variable}`}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
      </head>     
      <body>
        <ToasterProvider />
        {children}
      </body>
    </html>
  );
}
